### ISSUE TITLE
Where to get the PDF

### ISSUE THREAD

**Issue by dariyooo** [acoomans/kanjinetworks#1]
I know this repo is quite old, but do you by any chance have an idea where to get the PDF?

**Comment by acoomans** [comment]
The PDF is in the repo:github.comDistributed with permission of the author. On 22 Apr 2023, at 10:22, CaptainDario ***@***.***> wrote:﻿
I know this repo is quite old, but do you by any chance have an idea where to get the PDF?

**Comment by dariyooo** [comment]
Thank you very much!

Edit: Just in case somebody else stumbles upon this, [here is the PDF](https://github.com/acoomans/kanjinetworks/tree/master/kanjinetworks/data)
